name: Repo Visualizer

on:
  push:
    branches: [feat/actions]

jobs:
  repo-visualizer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@master

      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.8.2
        with:
          output_file: "report/diagram.svg"
